Port to Gtk3
sugarlabs/calendario pull request #2
Opened 2018-11-10 03:46 UTC by tonadev

### Explanation
Fix #1. This PR ports to Gtk3. 

### Reason
GTK+ 2 is end of life.
### Test result
No error related to the port to Gtk3.
```
tonadev@TDPC:~/Documents/Work/OpenSource/code_in/sugarlabs/calendario$ sugar-activity

(sugar-activity:3779): Gtk-WARNING **: 21:42:13.884: Theme parsing error: gtk-widgets.css:16:32: The style property GtkExpander:expander-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(sugar-activity:3779): Gtk-WARNING **: 21:42:13.884: Theme parsing error: gtk-widgets.css:17:35: The style property GtkExpander:expander-spacing is deprecated and shouldn't be used anymore. It will be removed in a future version

```

2018-11-10 08:20 UTC, rhl-bthr requested changes

2018-11-10 08:20 UTC, rhl-bthr commented on calendario.py
> -        self.options_expander = gtk.Expander(_("Options"))
`_()` should not be removed

2018-11-10 08:20 UTC, rhl-bthr commented on model.py
> +import gi
Why is this import required ?

2018-11-10 16:57 UTC, tonadev commented on calendario.py
> -        self.options_expander = gtk.Expander(_("Options"))
Done (8e36443603c6f21b3497532a1163c2e49c9356dd)

2018-11-10 16:59 UTC, tonadev commented on model.py
> +import gi
It's not, removed in 8e36443603c6f21b3497532a1163c2e49c9356dd

2018-11-10 17:59 UTC, pro-panda commented
Thanks @tonadev.
I have some general suggestions, (un) related to this port.
 * While running the activity, try out all its features. This will help in testing all segments of the code. (not sure you did this)
 * Run `flake8` and `autopep8` to ensure code standards are met. If there are any changes apart from your intended changes, include them in a separate commit. 
(not done here. There are some unused imports such as [this](https://github.com/sugarlabs/calendario/pull/2/files#diff-5b9afb05fb51af7fef9973427718e6b8R29)
 * Always link your PR to the issue. This helps in keeping conversations in sync and automatic closing of the issue if the PR gets merged (done here)

2018-11-12 00:36 UTC, quozl commented
Reviewed.

2018-12-10 04:29 UTC, rhl-bthr approved these changes

2018-12-10 04:29 UTC, merged